# Generated by Django 3.1.6 on 2021-07-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('designation', models.PositiveIntegerField(blank=True, choices=[(1, 'Unit Chief'), (2, 'Engineer'), (3, 'Engineer Geologist'), (4, 'Accountant'), (5, 'Administration')], null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Username')),
                ('full_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of birth')),
                ('identification', models.CharField(choices=[('CT', 'Citizenship'), ('PS', 'Passport'), ('OT', 'Others')], max_length=2, null=True)),
                ('id_number', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user-image')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='is_admin')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is_superuser')),
                ('is_permitted', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('username', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Username')),
                ('full_name', models.CharField(max_length=50, null=True, verbose_name='Full Name')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('image', models.ImageField(null=True, upload_to='user-image')),
                ('temporary_address', models.CharField(blank=True, max_length=150, null=True)),
                ('permanent_address', models.CharField(max_length=150, null=True)),
                ('date_joined', models.DateTimeField(null=True, verbose_name='Join Date')),
                ('leave_date', models.DateTimeField(blank=True, null=True, verbose_name='Leave Date')),
                ('is_transferred', models.BooleanField(default=False)),
                ('is_projecthead', models.BooleanField(default=False)),
                ('none', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'employee profile',
                'ordering': ['-id'],
            },
        ),
    ]
