from django.urls import path
from .views import *
from django.views.generic import TemplateView


urlpatterns = [
    # Material test
    path(
        "admin/construction/material/earth-filling/",
        EarthFillingListView.as_view(),
        name="earth-filling-list",
    ),
    path(
        "admin/construction/material/earth-filling/add",
        EarthFillingAddView.as_view(),
        name="earth-filling-add",
    ),
    path(
        "admin/construction/material/earth-filling/update/<int:pk>",
        EarthFillingUpdateView.as_view(),
        name="earth-filling-update",
    ),
    path(
        "admin/construction/material/earth-filling/delete/<int:pk>",
        EarthFillingDeleteView.as_view(),
        name="earth-filling-delete",
    ),
    # ----------EarthFillingURL Done------------------
    path(
        "admin/construction/material/face-slab-2a/",
        FaceSlabATestListView.as_view(),
        name="face-slab-2a-list",
    ),
    path(
        "admin/construction/material/face-slab-2a/add",
        FaceSlabATestAddView.as_view(),
        name="face-slab-2a-add",
    ),
    path(
        "admin/construction/material/face-slab-2a/update/<int:pk>",
        FaceSlabATestUpdateView.as_view(),
        name="face-slab-2a-update",
    ),
    path(
        "admin/construction/material/face-slab-2a/delete/<int:pk>",
        FaceSlabATestDeleteView.as_view(),
        name="face-slab-2a-delete",
    ),
    # --------------------- FaceSlab 2A done ---------------
    path(
        "admin/construction/material/face-slab-2b/",
        FaceSlabBTestListView.as_view(),
        name="face-slab-2b-list",
    ),
    path(
        "admin/construction/material/face-slab-2b/add",
        FaceSlabBTestAddView.as_view(),
        name="face-slab-2b-add",
    ),
    path(
        "admin/construction/material/face-slab-2b/update/<int:pk>",
        FaceSlabBTestUpdateView.as_view(),
        name="face-slab-2b-update",
    ),
    path(
        "admin/construction/material/face-slab-2b/delete/<int:pk>",
        FaceSlabBTestDeleteView.as_view(),
        name="face-slab-2b-delete",
    ),
    # ------------------Face Slab 2B Done-----------------
    path(
        "admin/construction/material/small-size-rock/",
        SmallRockTestListView.as_view(),
        name="small-size-rock-list",
    ),
    path(
        "admin/construction/material/small-size-rock/add",
        SmallRockTestAddView.as_view(),
        name="small-size-rock-add",
    ),
    path(
        "admin/construction/material/small-size-rock/update/<int:pk>",
        SmallRockTestUpdateView.as_view(),
        name="small-size-rock-update",
    ),
    path(
        "admin/construction/material/small-size-rock/delete/<int:pk>",
        SmallRockTestDeleteView.as_view(),
        name="small-size-rock-delete",
    ),
    # ------------- Small Size rock url DOne -------------------------
    path(
        "admin/construction/material/first-class-rock/",
        FirstClassTestListView.as_view(),
        name="first-class-rock-list",
    ),
    path(
        "admin/construction/material/first-class-rock/add",
        FirstClassTestAddView.as_view(),
        name="first-class-rock-add",
    ),
    path(
        "admin/construction/material/first-class-rock/update/<int:pk>",
        FirstClassTestUpdateView.as_view(),
        name="first-class-rock-update",
    ),
    path(
        "admin/construction/material/first-class-rock/delete/<int:pk>",
        FirstClassTestDeleteView.as_view(),
        name="first-class-rock-delete",
    ),
    # ---------- First class Rock ___________________
    path(
        "admin/construction/material/second-class-rock/",
        SecondClassTestListView.as_view(),
        name="second-class-rock-list",
    ),
    path(
        "admin/construction/material/second-class-rock/add",
        SecondClassTestAddView.as_view(),
        name="second-class-rock-add",
    ),
    path(
        "admin/construction/material/second-class-rock/update/<int:pk>",
        SecondClassTestUpdateView.as_view(),
        name="second-class-rock-update",
    ),
    path(
        "admin/construction/material/second-class-rock/delete/<int:pk>",
        SecondClassTestDeleteView.as_view(),
        name="second-class-rock-delete",
    ),
    # -------------------Second Class Rock -------------------
    path(
        "admin/construction/material/rock-fill/",
        RockFillTestListView.as_view(),
        name="rock-fill-list",
    ),
    path(
        "admin/construction/material/rock-fill/add",
        RockFillTestAddView.as_view(),
        name="rock-fill-add",
    ),
    path(
        "admin/construction/material/rock-fill/update/<int:pk>",
        RockFillTestUpdateView.as_view(),
        name="rock-fill-update",
    ),
    path(
        "admin/construction/material/rock-fill/delete/<int:pk>",
        RockFillTestDeleteView.as_view(),
        name="rock-fill-delete",
    ),
    # -------------------Rock Fill -------------------
    path(
        "admin/construction/material/concrete-aggregate-40mm/",
        ConcreteLargeTestListView.as_view(),
        name="concrete-aggregate-40mm-list",
    ),
    path(
        "admin/construction/material/concrete-aggregate-40mm/add",
        ConcreteLargeTestAddView.as_view(),
        name="concrete-aggregate-40mm-add",
    ),
    path(
        "admin/construction/material/concrete-aggregate-40mm/update/<int:pk>",
        ConcreteLargeTestUpdateView.as_view(),
        name="concrete-aggregate-40mm-update",
    ),
    path(
        "admin/construction/material/concrete-aggregate-40mm/delete/<int:pk>",
        ConcreteLargeTestDeleteView.as_view(),
        name="concrete-aggregate-40mm-delete",
    ),
    # ----------------------- Concreate 40 mm ---------------------
    path(
        "admin/construction/material/concrete-aggregate-20mm/",
        ConcreteMediumTestListView.as_view(),
        name="concrete-aggregate-20mm-list",
    ),
    path(
        "admin/construction/material/concrete-aggregate-20mm/add",
        ConcreteMediumTestAddView.as_view(),
        name="concrete-aggregate-20mm-add",
    ),
    path(
        "admin/construction/material/concrete-aggregate-20mm/update/<int:pk>",
        ConcreteMediumTestUpdateView.as_view(),
        name="concrete-aggregate-20mm-update",
    ),
    path(
        "admin/construction/material/concrete-aggregate-20mm/delete/<int:pk>",
        ConcreteMediumTestDeleteView.as_view(),
        name="concrete-aggregate-20mm-delete",
    ),
    # ----------------------- Concreate 20 mm done ---------------------
    path(
        "admin/construction/material/concrete-aggregate-10mm/",
        ConcreteSmallTestListView.as_view(),
        name="concrete-aggregate-10mm-list",
    ),
    path(
        "admin/construction/material/concrete-aggregate-10mm/add",
        ConcreteSmallTestAddView.as_view(),
        name="concrete-aggregate-10mm-add",
    ),
    path(
        "admin/construction/material/concrete-aggregate-10mm/update/<int:pk>",
        ConcreteSmallTestUpdateView.as_view(),
        name="concrete-aggregate-10mm-update",
    ),
    path(
        "admin/construction/material/concrete-aggregate-10mm/delete/<int:pk>",
        ConcreteSmallTestDeleteView.as_view(),
        name="concrete-aggregate-10mm-delete",
    ),
    # ----------------------- Concreate 10mm Done ---------------------
    path(
        "admin/construction/material/fine-aggregate/",
        FineAggregateTestListView.as_view(),
        name="fine-aggregate-list",
    ),
    path(
        "admin/construction/material/fine-aggregate/add",
        FineAggregateTestAddView.as_view(),
        name="fine-aggregate-add",
    ),
    path(
        "admin/construction/material/fine-aggregate/update/<int:pk>",
        FineAggregateTestUpdateView.as_view(),
        name="fine-aggregate-update",
    ),
    path(
        "admin/construction/material/fine-aggregate/delete/<int:pk>",
        FineAggregateTestDeleteView.as_view(),
        name="fine-aggregate-delete",
    ),
    # ------------------ Fine aggregate Done ----------------
    path(
        "admin/construction/material/cement/",
        CementTestListView.as_view(),
        name="cement-list",
    ),
    path(
        "admin/construction/material/cement/add",
        CementTestAddView.as_view(),
        name="cement-add",
    ),
    path(
        "admin/construction/material/cement/update/<int:pk>",
        CementTestUpdateView.as_view(),
        name="cement-update",
    ),
    path(
        "admin/construction/material/cement/delete/<int:pk>",
        CementTestDeleteView.as_view(),
        name="cement-delete",
    ),
    # --------------- Cement Test Done --------------------
    path(
        "admin/construction/material/granular/",
        GranularTestListView.as_view(),
        name="granular-list",
    ),
    path(
        "admin/construction/material/granular/add",
        GranularTestAddView.as_view(),
        name="granular-add",
    ),
    path(
        "admin/construction/material/granular/update/<int:pk>",
        GranularTestUpdateView.as_view(),
        name="granular-update",
    ),
    path(
        "admin/construction/material/granular/delete/<int:pk>",
        GranularTestDeleteView.as_view(),
        name="granular-delete",
    ),
    # ---------------------------- Granular Test Done --------------
    # ------------------ Concrete Test Url below---------------
    path(
        "admin/construction/work/concrete-test/",
        ConcreteTestView.as_view(),
        name="concrete-test-list",
    ),
    path(
        "admin/construction/work/concrete-test/add",
        ConcreteTestAddView.as_view(),
        name="concrete-test-add",
    ),
    path(
        "admin/construction/work/concrete-test/update/<int:pk>",
        ConcreteTestUpdateView.as_view(),
        name="concrete-test-update",
    ),
    path(
        "construction/work/concrete-test/delete/<int:pk>",
        ConcreteTestDeleteView.as_view(),
        name="concrete-test-delete",
    ),
    # ----------------------Concrete test done ------------------------------
    path(
        "admin/construction/work/compaction-test/",
        CompactionTestListView.as_view(),
        name="compaction-test-list",
    ),
    path(
        "admin/construction/work/compaction-test/add",
        CompactionTestAddView.as_view(),
        name="compaction-test-add",
    ),
    path(
        "admin/construction/work/compaction-test/update/<int:pk>",
        CompactionTestUpdateView.as_view(),
        name="compaction-test-update",
    ),
    path(
        "admin/construction/work/compaction-test/delete/<int:pk>",
        CompactionTestDeleteView.as_view(),
        name="compaction-test-delete",
    ),
    # -------------------------------- COmpaction Test URL Done-------------------------
    path(
        "admin/construction/work/grouting-test/",
        GroutingTestListView.as_view(),
        name="grouting-test-list",
    ),
    path(
        "admin/construction/work/grouting-test/add",
        GroutingTestAddView.as_view(),
        name="grouting-test-add",
    ),
    path(
        "admin/construction/work/grouting-test/update/<int:pk>",
        GroutingTestUpdateView.as_view(),
        name="grouting-test-update",
    ),
    path(
        "admin/construction/work/grouting-test/delete/<int:pk>",
        GroutingTestDeleteView.as_view(),
        name="grouting-test-delete",
    ),
    # -------------------------------- Grouting Test URL Done-------------------------
    path(
        "admin/construction/work/copper-test/",
        CopperTestListView.as_view(),
        name="copper-test-list",
    ),
    path(
        "admin/construction/work/copper-test/add",
        CopperTestAddView.as_view(),
        name="copper-test-add",
    ),
    path(
        "admin/construction/work/copper-test/update/<int:pk>",
        CopperTestUpdateView.as_view(),
        name="copper-test-update",
    ),
    path(
        "admin/construction/work/copper-test/delete/<int:pk>",
        CopperTestDeleteView.as_view(),
        name="copper-test-delete",
    ),
    # -------------------------------- Copper Water Test URL Done-------------------------
    path(
        "admin/construction/work/permeability-test/",
        PermeabilityTestListView.as_view(),
        name="permeability-test-list",
    ),
    path(
        "admin/construction/work/permeability-test/add",
        PermeabilityTestAddView.as_view(),
        name="permeability-test-add",
    ),
    path(
        "admin/construction/work/permeability-test/update/<int:pk>",
        PermeabilityTestUpdateView.as_view(),
        name="permeability-test-update",
    ),
    path(
        "admin/construction/work/permeability-test/delete/<int:pk>",
        PermeabilityTestDeleteView.as_view(),
        name="permeability-test-delete",
    ),
    # -------------------------------- Permeability Test URL Done-------------------------
    path(
        "admin/construction/work/geophysical-test/",
        GeophysicalTestListView.as_view(),
        name="geophysical-test-list",
    ),
    path(
        "admin/construction/work/geophysical-test/add",
        GeophysicalTestAddView.as_view(),
        name="geophysical-test-add",
    ),
    path(
        "admin/construction/work/geophysical-test/update/<int:pk>",
        GeophysicalTestUpdateView.as_view(),
        name="geophysical-test-update",
    ),
    path(
        "admin/construction/work/geophysical-test/delete/<int:pk>",
        GeophysicalTestDeleteView.as_view(),
        name="geophysical-test-delete",
    ),
    # -------------------------------- Geophysical Test URL Done-------------------------
    path(
        "admin/construction/work/core-drill/",
        CoreDrillTestListView.as_view(),
        name="core-drill-list",
    ),
    path(
        "admin/construction/work/core-drill/add",
        CoreDrillTestAddView.as_view(),
        name="core-drill-add",
    ),
    path(
        "admin/construction/work/core-drill/update/<int:pk>",
        CoreDrillTestUpdateView.as_view(),
        name="core-drill-update",
    ),
    path(
        "admin/construction/work/core-drill/delete/<int:pk>",
        CoreDrillTestDeleteView.as_view(),
        name="core-drill-delete",
    ),
    # -------------------------------- Core Drill Test URL Done-------------------------
    path(
        "admin/construction/documentation-test/",
        DocumentationTestListView.as_view(),
        name="documentation-test-list",
    ),
    path(
        "admin/construction/documentation-test/add",
        DocumentationTestAddView.as_view(),
        name="documentation-test-add",
    ),
    path(
        "admin/construction/documentation-test/update/<int:pk>",
        DocumentationTestUpdateView.as_view(),
        name="documentation-test-update",
    ),
    path(
        "admin/construction/documentation-test/delete/<int:pk>",
        DocumentationTestDeleteView.as_view(),
        name="documentation-test-delete",
    ),
    # -------------------------------- Documentation Test URL Done-------------------------
    path(
        "admin/construction/equipment/earth-equipment/",
        EarthEquipmentListView.as_view(),
        name="earth-equipment-list",
    ),
    path(
        "admin/construction/equipment/earth-equipment/add",
        EarthEquipmentAddView.as_view(),
        name="earth-equipment-add",
    ),
    path(
        "admin/construction/equipment/earth-equipment/update/<int:pk>",
        EarthEquipmentUpdateView.as_view(),
        name="earth-equipment-update",
    ),
    path(
        "admin/construction/equipment/earth-equipment/delete/<int:pk>",
        EarthEquipmentDeleteView.as_view(),
        name="earth-equipment-delete",
    ),
    # -------------------------------- Earth Equipment Test URL Done-------------------------
    path(
        "admin/construction/equipment/concreting-equipment/",
        ConcretingEquipmentListView.as_view(),
        name="concreting-equipment-list",
    ),
    path(
        "admin/construction/equipment/concreting-equipment/add",
        ConcretingEquipmentAddView.as_view(),
        name="concreting-equipment-add",
    ),
    path(
        "admin/construction/equipment/concreting-equipment/update/<int:pk>",
        ConcretingEquipmentUpdateView.as_view(),
        name="concreting-equipment-update",
    ),
    path(
        "admin/construction/equipment/concreting-equipment/delete/<int:pk>",
        ConcretingEquipmentDeleteView.as_view(),
        name="concreting-equipment-delete",
    ),
    # -------------------------------- Concreting Equipment Test URL Done-------------------------
    path(
        "admin/construction/equipment/grouting-equipment/",
        GroutingEquipmentListView.as_view(),
        name="grouting-equipment-list",
    ),
    path(
        "admin/construction/equipment/grouting-equipment/add",
        GroutingEquipmentAddView.as_view(),
        name="grouting-equipment-add",
    ),
    path(
        "admin/construction/equipment/grouting-equipment/update/<int:pk>",
        GroutingEquipmentUpdateView.as_view(),
        name="grouting-equipment-update",
    ),
    path(
        "admin/construction/equipment/grouting-equipment/delete/<int:pk>",
        GroutingEquipmentDeleteView.as_view(),
        name="grouting-equipment-delete",
    ),
    # -------------------------------- Grouting Equipment Test URL Done-------------------------
    path(
        "admin/construction/equipment/brazing-equipment/",
        BrazingEquipmentListView.as_view(),
        name="brazing-equipment-list",
    ),
    path(
        "admin/construction/equipment/brazing-equipment/add",
        BrazingEquipmentAddView.as_view(),
        name="brazing-equipment-add",
    ),
    path(
        "admin/construction/equipment/brazing-equipment/update/<int:pk>",
        BrazingEquipmentUpdateView.as_view(),
        name="brazing-equipment-update",
    ),
    path(
        "admin/construction/equipment/brazing-equipment/delete/<int:pk>",
        BrazingEquipmentDeleteView.as_view(),
        name="brazing-equipment-delete",
    ),
    # -------------------------------- Brazing Equipment Test URL Done-------------------------
    # -------------------------------- design drawing start-------------------------
    path(
        "admin/construction/design-drawing/",
        DesignDrawingListView.as_view(),
        name="design-drawing-list",
    ),
    path(
        "admin/construction/equipment/design-drawing/add",
        DesignDrawingAddView.as_view(),
        name="design-drawing-create",
    ),
    path(
        "admin/construction/equipment/design-drawing/update/<int:pk>",
        DesignDrawingUpdateView.as_view(),
        name="design-drawing-update",
    ),
    path(
        "admin/construction/equipment/design-drawing/delete/<int:pk>",
        DesignDrawingDeleteView.as_view(),
        name="design-drawing-delete",
    ),
    # -------------------------------- design drawing end-------------------------
    # -------------------------------- mos start-------------------------
    path(
        "admin/construction/mos/", MethodOfStatementListView.as_view(), name="mos-list"
    ),
    path(
        "admin/construction/mos/add",
        MethodOfStatementAddView.as_view(),
        name="mos-create",
    ),
    path(
        "admin/construction/mos/update/<int:pk>",
        MethodOfStatementUpdateView.as_view(),
        name="mos-update",
    ),
    path(
        "admin/construction/mos/delete/<int:pk>",
        MethodOfStatementDeleteView.as_view(),
        name="mos-delete",
    ),
    # -------------------------------- mos end-------------------------
    # -------------------------------- report start-------------------------
    path("admin/construction/report/", ReportsListView.as_view(), name="reports-list"),
    path(
        "admin/construction/report/add",
        ReportAddView.as_view(),
        name="report-create",
    ),
    path(
        "admin/construction/report/update/<int:pk>",
        ReportUpdateView.as_view(),
        name="report-update",
    ),
    path(
        "admin/construction/report/delete/<int:pk>",
        ReportDeleteView.as_view(),
        name="report-delete",
    ),
    # -------------------------------- work footage start -------------------------
    path(
        "admin/construction/work-footage/",
        WorkFootageListView.as_view(),
        name="work-footage-list",
    ),
    path(
        "admin/construction/work-footage/add",
        WorkFootageAddView.as_view(),
        name="work-footage-create",
    ),
    path(
        "admin/construction/work-footage/update/<int:pk>",
        WorkFootageUpdateView.as_view(),
        name="work-footage-update",
    ),
    path(
        "admin/construction/work-footage/delete/<int:pk>",
        WorkFootageDeleteView.as_view(),
        name="work-footage-delete",
    ),
    # -------------------------------- work footage end -------------------------
    # -------------------------------- test footage start -------------------------
    path(
        "admin/construction/test-footage/",
        TestFootageListView.as_view(),
        name="test-footage-list",
    ),
    path(
        "admin/construction/test-footage/add",
        TestFootageAddView.as_view(),
        name="test-footage-create",
    ),
    path(
        "admin/construction/test-footage/update/<int:pk>",
        TestFootageUpdateView.as_view(),
        name="test-footage-update",
    ),
    path(
        "admin/construction/test-footage/delete/<int:pk>",
        TestFootageDeleteView.as_view(),
        name="test-footage-delete",
    ),
    # -------------------------------- test footage end -------------------------
    path(
        "admin/construction/equipment/survey-equipment/",
        SurveyEquipmentListView.as_view(),
        name="survey-equipment-list",
    ),
    path(
        "admin/construction/equipment/survey-equipment/add",
        SurveyEquipmentAddView.as_view(),
        name="survey-equipment-add",
    ),
    path(
        "admin/construction/equipment/survey-equipment/update/<int:pk>",
        SurveyEquipmentUpdateView.as_view(),
        name="survey-equipment-update",
    ),
    path(
        "admin/construction/equipment/survey-equipment/delete/<int:pk>",
        SurveyEquipmentDeleteView.as_view(),
        name="survey-equipment-delete",
    ),
    path(
        "admin/construction/equipment/lab-equipment/",
        LabEquipmentListView.as_view(),
        name="lab-equipment-list",
    ),
    path(
        "admin/construction/equipment/lab-equipment/add",
        LabEquipmentAddView.as_view(),
        name="lab-equipment-add",
    ),
    path(
        "admin/construction/equipment/lab-equipment/update/<int:pk>",
        LabEquipmentUpdateView.as_view(),
        name="lab-equipment-update",
    ),
    path(
        "admin/construction/equipment/lab-equipment/delete/<int:pk>",
        LabEquipmentDeleteView.as_view(),
        name="lab-equipment-delete",
    ),
    path(
        "admin/construction/equipment/geophysical-equipment/",
        GeophysicalEquipmentListView.as_view(),
        name="geophysical-equipment-list",
    ),
    path(
        "admin/construction/equipment/geophysical-equipment/add",
        GeophysicalEquipmentAddView.as_view(),
        name="geophysical-equipment-add",
    ),
    path(
        "admin/construction/equipment/geophysical-equipment/update/<int:pk>",
        GeophysicalEquipmentUpdateView.as_view(),
        name="geophysical-equipment-update",
    ),
    path(
        "admin/construction/equipment/geophysical-equipment/delete/<int:pk>",
        GeophysicalEquipmentDeleteView.as_view(),
        name="geophysical-equipment-delete",
    ),
]
