# Generated by Django 3.1.6 on 2021-09-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DamLiteraures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'dam_literatures',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DamSalientFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_dam_or_reservoir', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('main_purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_of_dam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('as_per_size', models.CharField(max_length=50)),
                ('as_per_construction_material', models.CharField(max_length=50)),
                ('governing_icold_criteria_for_large_dams', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'dam_salient_features',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='NameOfDam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60, null=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'name_of_dam',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StorageProjectInPipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_dam_or_reservoir', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('main_purpose', models.CharField(blank=True, max_length=50, null=True)),
                ('volume_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height_of_dam', models.DecimalField(decimal_places=2, max_digits=10)),
                ('as_per_size', models.CharField(max_length=50)),
                ('as_per_construction_material', models.CharField(max_length=50)),
                ('governing_icold_criteria_for_large_dams', models.CharField(blank=True, max_length=120, null=True)),
            ],
            options={
                'db_table': 'storage_project_in_pipeline',
                'ordering': ['-id'],
            },
        ),
    ]
