# Generated by Django 3.1.6 on 2021-11-16 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damknowledge', '0004_storageprojectinpipeline_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='damliteraures',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='damliteratures/image/', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='damliteraures',
            name='link',
            field=models.URLField(blank=True, max_length=800, null=True, verbose_name='Link'),
        ),
    ]
