# Generated by Django 3.1.6 on 2021-09-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_homenotice_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentactivities',
            name='display',
            field=models.BooleanField(default=False),
        ),
    ]
