# Generated by Django 3.1.6 on 2021-09-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_recentactivities_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homenotice',
            name='display',
            field=models.BooleanField(default=False, verbose_name='Please check the box to display notice in homepage.'),
        ),
        migrations.AlterField(
            model_name='message',
            name='designation',
            field=models.CharField(choices=[('U', 'Unit Chief'), ('E', 'Engineer')], max_length=1, null=True),
        ),
    ]
