# Generated by Django 3.0.3 on 2021-04-28 07:18

import contracts.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_id', models.CharField(max_length=100, verbose_name='Contract ID')),
                ('project_name', models.CharField(max_length=500, verbose_name='Contract Name')),
                ('work_name', models.CharField(max_length=500, verbose_name='Work Name')),
                ('contractor_detail', models.CharField(max_length=1000, verbose_name='Contractor Name and Address')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount of agreement')),
                ('date_of_agreement', models.DateField(verbose_name='Date of Agreement')),
                ('date_of_completion', models.DateField(verbose_name='Date of Completion as Agreement')),
                ('date_of_completion_revised', jsonfield.fields.JSONField(blank=True, default=contracts.models.revised_completion, null=True, verbose_name='Date of Completion (Revised)')),
                ('actual_expenditure', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Actual expenditure')),
                ('current_status', models.CharField(choices=[('C', 'Completed'), ('O', 'Ongoing')], max_length=2, verbose_name='Current Project Status')),
                ('contractor_liability_status', models.CharField(choices=[('C', 'Completed'), ('O', 'Ongoing')], max_length=2, verbose_name='Contractor Liability Status')),
                ('works_completed', models.TextField(verbose_name='Works Completed')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
            },
        ),
        migrations.CreateModel(
            name='ContractProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_extended_on_original_schedule', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Time Extended based on original Schedule')),
                ('time_elapsed_on_revise_schedule', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Time Elapsed based on revised schedule')),
                ('time_remaining_on_extended_schedule', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Time Remaining based on extended schedule')),
                ('financial_progress_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Financial Progress Amount')),
                ('financial_percent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Financial Percent Amount')),
                ('financial_progress_date', models.DateField(blank=True, null=True, verbose_name='Last payment Date')),
                ('physical_percent_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Physical Percent Amount')),
                ('physical_progress_date', models.DateField(blank=True, null=True, verbose_name='Physical Progress as of date')),
                ('progress_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Progress Status')),
                ('remarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Remarks')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_progress', to='contracts.Contract', verbose_name='contract')),
            ],
            options={
                'verbose_name': 'Contract Progress',
                'verbose_name_plural': 'Contract Progresses',
            },
        ),
        migrations.CreateModel(
            name='ContractFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dam_type', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('top_length', models.CharField(blank=True, max_length=255, null=True)),
                ('crest_elevation', models.CharField(blank=True, max_length=255, null=True)),
                ('upstream_slope', models.CharField(blank=True, max_length=255, null=True)),
                ('downstream_slope', models.CharField(blank=True, max_length=255, null=True)),
                ('crest_width', models.CharField(blank=True, max_length=255, null=True)),
                ('concrete_face_thickness', models.CharField(blank=True, max_length=255, null=True)),
                ('reservoir_volume', models.CharField(blank=True, max_length=255, null=True)),
                ('norma_water_level', models.CharField(blank=True, max_length=255, null=True)),
                ('freeboard', models.CharField(blank=True, max_length=255, null=True)),
                ('saddle_dam', models.CharField(blank=True, max_length=255, null=True)),
                ('dam_volume', models.CharField(blank=True, max_length=255, null=True)),
                ('full_supply_level', models.CharField(blank=True, max_length=255, null=True)),
                ('design_discharge', models.CharField(blank=True, max_length=255, null=True)),
                ('power_production', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.CharField(blank=True, max_length=255, null=True)),
                ('reservoir_surface_area', models.CharField(blank=True, max_length=255, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_feature', to='contracts.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='ContractDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, null=True)),
                ('location_and_accessibility', models.TextField(blank=True, null=True)),
                ('work_component', models.TextField(blank=True, null=True)),
                ('design_and_quality', models.TextField(blank=True, null=True)),
                ('environmental_aspects', models.TextField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_detail', to='contracts.Contract')),
            ],
            options={
                'verbose_name': 'Contract Detail',
                'verbose_name_plural': 'Contract Detail',
            },
        ),
    ]
