# Generated by Django 3.1.6 on 2021-09-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20210905_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='date_of_completion_revised',
        ),
    ]
