# Generated by Django 3.1.6 on 2021-09-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_auto_20210916_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractprogress',
            name='financial_percent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Financial Percent Amount'),
        ),
        migrations.AlterField(
            model_name='contractprogress',
            name='physical_percent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Physical Percent Amount'),
        ),
    ]
