# Generated by Django 3.1.6 on 2021-09-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20210916_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='works_completed',
            field=models.CharField(max_length=500, verbose_name='Works Completed'),
        ),
        migrations.AlterField(
            model_name='contractprogress',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
    ]
