# Generated by Django 3.1.6 on 2021-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_auto_20210918_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractprogress',
            name='financial_percent_amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=30, null=True, verbose_name='Financial Percent Amount'),
        ),
    ]
