# Generated by Django 3.1.6 on 2021-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_auto_20210918_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractprogress',
            name='physical_percent_amount',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=30, null=True, verbose_name='Physical Percent Amount'),
        ),
    ]
