# Generated by Django 3.1.6 on 2021-07-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salientfeatures',
            name='dam_crest_elevation',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Dam crest elevation'),
        ),
        migrations.AlterField(
            model_name='contractdetail',
            name='client',
            field=models.CharField(max_length=60, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='salientfeatures',
            name='crest_width',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Crest Width'),
        ),
    ]
