# Generated by Django 3.1.6 on 2021-07-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0002_auto_20210703_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='salientfeatures',
            name='reservoir_surface_area_at_fsl',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Reservoir surface area at FSL'),
        ),
    ]
