# Generated by Django 3.1.6 on 2021-07-04 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0003_salientfeatures_reservoir_surface_area_at_fsl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Introduction',
            new_name='DamIntroduction',
        ),
        migrations.AlterModelOptions(
            name='damintroduction',
            options={'ordering': ['-id'], 'verbose_name_plural': 'DamIntroduction'},
        ),
    ]
