# Generated by Django 3.1.6 on 2021-07-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0004_auto_20210704_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damintroduction',
            name='content',
        ),
        migrations.RemoveField(
            model_name='damintroduction',
            name='image',
        ),
        migrations.CreateModel(
            name='IntoductionOfDam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True, verbose_name='Content')),
                ('image', models.FileField(blank=True, null=True, upload_to='introduction')),
                ('introduction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='introduction_of_dam', to='dam.damintroduction')),
            ],
            options={
                'verbose_name_plural': 'IntoductionOfDam',
                'ordering': ['-id'],
            },
        ),
    ]
