# Generated by Django 3.1.6 on 2021-07-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0005_auto_20210704_1045'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntoductionOfDam',
            new_name='IntroductionOfDam',
        ),
        migrations.AlterModelOptions(
            name='introductionofdam',
            options={'ordering': ['-id'], 'verbose_name_plural': 'IntroductionOfDam'},
        ),
    ]
