# Generated by Django 3.1.6 on 2021-09-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0007_auto_20210918_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdetail',
            name='Name_of_work',
            field=models.CharField(max_length=250, verbose_name='Name of Work'),
        ),
    ]
