# Generated by Django 3.1.6 on 2021-12-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0010_auto_20211004_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='MajorWorkComponentsDhapDam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_dam', models.CharField(choices=[('M', 'Main Dam'), ('S', 'Saddle Dam')], max_length=2, null=True, verbose_name='Work Components Dam Type')),
                ('title', models.CharField(max_length=60, verbose_name='Sub Dam Name')),
                ('image', models.FileField(blank=True, null=True, upload_to='components')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('introduction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_components_dhapdam', to='dam.damintroduction')),
            ],
            options={
                'verbose_name_plural': 'MajorWorkComponents Dhapdam',
                'ordering': ['-id'],
            },
        ),
    ]
