# Generated by Django 3.1.6 on 2021-12-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam', '0011_majorworkcomponentsdhapdam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='majorworkcomponentsdhapdam',
            name='image',
            field=models.FileField(default=1, upload_to='components'),
            preserve_default=False,
        ),
    ]
