# Generated by Django 3.1.6 on 2021-06-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fiscal Year')),
                ('title', models.CharField(blank=True, max_length=60, null=True, verbose_name='Title')),
                ('files', models.FileField(upload_to='adminstration_and_account/uploaded_files/')),
                ('types', models.CharField(choices=[('Cu', 'Current Budget'), ('Ca', 'Capital Budget')], default=1, max_length=2, verbose_name='Type of Files')),
            ],
            options={
                'verbose_name': 'Account Upload file',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AdminstrationUploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fiscal Year')),
                ('title', models.CharField(blank=True, max_length=60, null=True, verbose_name='Title')),
                ('files', models.FileField(upload_to='adminstration_and_account/uploaded_files/')),
            ],
            options={
                'verbose_name': 'Adminstration upload file',
            },
        ),
        migrations.CreateModel(
            name='CapitalBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=100, null=True, verbose_name='Fiscal Year')),
                ('annual_budget', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Annual Budget')),
                ('expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expenditure')),
                ('remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Remaning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'capital Budget',
            },
        ),
        migrations.CreateModel(
            name='Chalani',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chalani_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Chalani number')),
                ('date', models.DateField(verbose_name='Chalani Date')),
                ('patra_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prapta Patra number')),
                ('sender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prapta sender office/person')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prapta sender office/person address')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prapta Subject')),
                ('medium', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sending Medium')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remark')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chalani-images', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Chalanis',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CitizenCharter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of Citizen Charter')),
                ('file', models.FileField(blank=True, null=True, upload_to='citizen-charter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Citizen Charter',
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, null=True, verbose_name='Address')),
                ('phone1', models.CharField(max_length=16, null=True, verbose_name='Phone1')),
                ('phone2', models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone2')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Site url')),
            ],
            options={
                'verbose_name_plural': 'CompanyProfile',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='construction')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='construction')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='construction')),
            ],
            options={
                'verbose_name_plural': 'Construction Work',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('message', models.TextField(verbose_name='Message')),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact us',
            },
        ),
        migrations.CreateModel(
            name='CurrentBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(max_length=100, null=True, verbose_name='Fiscal Year')),
                ('annual_budget', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Annual Budget')),
                ('expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Expenditure')),
                ('remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Remaning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Current Budget',
            },
        ),
        migrations.CreateModel(
            name='Darta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darta_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Darta number')),
                ('date', models.DateField(verbose_name='Darta Date')),
                ('patra_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prapta Patra number')),
                ('cha_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prapta Patra Chha number')),
                ('patra_received_date', models.DateField(verbose_name='Patra Received Date')),
                ('sender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Prapta sender office/person')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prapta sender office/person address')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prapta Subject')),
                ('medium', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sending Medium')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remark')),
                ('image', models.ImageField(blank=True, null=True, upload_to='patra-images', verbose_name='Image')),
            ],
            options={
                'verbose_name_plural': 'Dartas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True, verbose_name='Type')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('file', models.FileField(upload_to='downloads')),
                ('size', models.CharField(max_length=50, verbose_name='Size of file')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='URL of file')),
            ],
            options={
                'verbose_name_plural': 'Downloads',
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('target', models.BigIntegerField(verbose_name='Yearly Target')),
            ],
        ),
        migrations.CreateModel(
            name='HomepageSliderImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='homepage-slider')),
            ],
            options={
                'verbose_name_plural': 'Homepage Slider Images',
            },
        ),
        migrations.CreateModel(
            name='ImportantLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(blank=True, max_length=200, null=True, verbose_name='Content')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name_plural': 'Important Links',
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Introduction')),
                ('image', models.FileField(blank=True, null=True, upload_to='introduction')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('image', models.FileField(null=True, upload_to='photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Photos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('file', models.FileField(blank=True, null=True, upload_to='policy', verbose_name='Name of File')),
                ('types', models.CharField(choices=[('1', 'Act and Regulations'), ('2', 'Startegy,Plans and Policies')], default=1, max_length=2, verbose_name='Type of Policy/Law')),
            ],
            options={
                'verbose_name_plural': 'Policy/Law',
            },
        ),
        migrations.CreateModel(
            name='Reservoir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='reservoir')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='reservoir')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='reservoir')),
            ],
            options={
                'verbose_name_plural': 'Reservoir',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StakeHolders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('content', models.TextField(blank=True, max_length=200, null=True, verbose_name='Content')),
                ('image', models.ImageField(upload_to='stakeholders')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link')),
            ],
            options={
                'verbose_name_plural': 'StakeHolders',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Name of Organization Structure')),
                ('file', models.FileField(blank=True, null=True, upload_to='structure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'organization structure',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('link', models.URLField(max_length=500, null=True, verbose_name='Videos Url')),
                ('thumbnail', models.ImageField(null=True, upload_to='thumbnail', verbose_name='Thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Videos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_visited', models.TextField()),
                ('event_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdTrimester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trimester Name')),
                ('month1', models.CharField(blank=True, choices=[('9', 'Chaitra'), ('10', 'Baisakh'), ('11', 'Jestha'), ('12', 'Ashar')], max_length=2, null=True, verbose_name='Month 1')),
                ('month1_periodic_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month1 Periodic Amount')),
                ('month1_cumulative_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month1 cumulative Amount')),
                ('month2', models.CharField(blank=True, choices=[('9', 'Chaitra'), ('10', 'Baisakh'), ('11', 'Jestha'), ('12', 'Ashar')], max_length=2, null=True, verbose_name='Month 2')),
                ('month2_periodic_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month2 Periodic Amount')),
                ('month2_cumulative_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month2 cumulative Amount')),
                ('month3', models.CharField(blank=True, choices=[('9', 'Chaitra'), ('10', 'Baisakh'), ('11', 'Jestha'), ('12', 'Ashar')], max_length=2, null=True, verbose_name='Month 3')),
                ('month3_periodic_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month3 Periodic Amount')),
                ('month3_cumulative_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month3 cumulative Amount')),
                ('month4', models.CharField(blank=True, choices=[('9', 'Chaitra'), ('10', 'Baisakh'), ('11', 'Jestha'), ('12', 'Ashar')], max_length=2, null=True, verbose_name='Month 4')),
                ('month4_periodic_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month4 Periodic Amount')),
                ('month4_cumulative_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month4 cumulative Amount')),
                ('trimester_periodic', models.BigIntegerField(blank=True, null=True, verbose_name='trimester Periodic Amount')),
                ('trimester_cumulative', models.BigIntegerField(blank=True, null=True, verbose_name='trimester cumulative Amount')),
                ('periodic_target', models.BigIntegerField(blank=True, null=True, verbose_name='Periodic Target Amount')),
                ('periodic_percentage_financial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Periodic Percentage')),
                ('yearly_percentage_financial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yearly Percentage')),
                ('periodic_physical_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Periodic Physical Progress')),
                ('cumulative_physical_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cumulative Physical Progress')),
                ('overrall', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Overall')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_trimester', to='company.fiscalyear')),
            ],
        ),
        migrations.CreateModel(
            name='SecondTrimester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trimester Name')),
                ('month1', models.CharField(blank=True, choices=[('5', 'Mangsir'), ('6', 'Paush'), ('7', 'Magh'), ('8', 'Falgun')], max_length=2, null=True, verbose_name='Month 1')),
                ('month1_periodic_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month1 Periodic Amount')),
                ('month1_cumulative_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month1 cumulative Amount')),
                ('month2', models.CharField(blank=True, choices=[('5', 'Mangsir'), ('6', 'Paush'), ('7', 'Magh'), ('8', 'Falgun')], max_length=2, null=True, verbose_name='Month 2')),
                ('month2_periodic_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month2 Periodic Amount')),
                ('month2_cumulative_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month2 cumulative Amount')),
                ('month3', models.CharField(blank=True, choices=[('5', 'Mangsir'), ('6', 'Paush'), ('7', 'Magh'), ('8', 'Falgun')], max_length=2, null=True, verbose_name='Month 3')),
                ('month3_periodic_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month3 Periodic Amount')),
                ('month3_cumulative_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month3 cumulative Amount')),
                ('month4', models.CharField(blank=True, choices=[('5', 'Mangsir'), ('6', 'Paush'), ('7', 'Magh'), ('8', 'Falgun')], max_length=2, null=True, verbose_name='Month 4')),
                ('month4_periodic_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month4 Periodic Amount')),
                ('month4_cumulative_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month4 cumulative Amount')),
                ('trimester_periodic', models.BigIntegerField(blank=True, null=True, verbose_name='trimester Periodic Amount')),
                ('trimester_cumulative', models.BigIntegerField(blank=True, null=True, verbose_name='trimester cumulative Amount')),
                ('periodic_target', models.BigIntegerField(blank=True, null=True, verbose_name='Periodic Target Amount')),
                ('periodic_percentage_financial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Periodic Percentage')),
                ('yearly_percentage_financial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yearly Percentage')),
                ('periodic_physical_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Periodic Physical Progress')),
                ('cumulative_physical_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cumulative Physical Progress')),
                ('overrall', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Overall')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_trimester', to='company.fiscalyear')),
            ],
        ),
        migrations.CreateModel(
            name='FirstTrimester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trimester Name')),
                ('month1', models.CharField(blank=True, choices=[('1', 'Shrawan'), ('2', 'Bhadra'), ('3', 'Ashoj'), ('4', 'Kartik')], max_length=2, null=True, verbose_name='Month 1')),
                ('month1_periodic_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month1 Periodic Amount')),
                ('month1_cumulative_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month1 cumulative Amount')),
                ('month2', models.CharField(blank=True, choices=[('1', 'Shrawan'), ('2', 'Bhadra'), ('3', 'Ashoj'), ('4', 'Kartik')], max_length=2, null=True, verbose_name='Month 2')),
                ('month2_periodic_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month2 Periodic Amount')),
                ('month2_cumulative_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month2 cumulative Amount')),
                ('month3', models.CharField(blank=True, choices=[('1', 'Shrawan'), ('2', 'Bhadra'), ('3', 'Ashoj'), ('4', 'Kartik')], max_length=2, null=True, verbose_name='Month 3')),
                ('month3_periodic_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month3 Periodic Amount')),
                ('month3_cumulative_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month3 Cumulative Amount')),
                ('month4', models.CharField(blank=True, choices=[('1', 'Shrawan'), ('2', 'Bhadra'), ('3', 'Ashoj'), ('4', 'Kartik')], max_length=2, null=True, verbose_name='Month 4')),
                ('month4_periodic_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month4 Periodic Amount')),
                ('month4_cumulative_amount', models.BigIntegerField(blank=True, null=True, verbose_name='Month4 Cumulative Amount')),
                ('trimester_periodic', models.BigIntegerField(blank=True, null=True, verbose_name='trimester Periodic Amount')),
                ('trimester_cumulative', models.BigIntegerField(blank=True, null=True, verbose_name='trimester cumulative Amount')),
                ('periodic_target', models.BigIntegerField(blank=True, null=True, verbose_name='Periodic Target Amount')),
                ('periodic_percentage_financial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Periodic Percentage')),
                ('yearly_percentage_financial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Yearly Percentage')),
                ('periodic_physical_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Periodic Physical Progress')),
                ('cumulative_physical_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cumulative Physical Progress')),
                ('overrall', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Overall')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_trimester', to='company.fiscalyear')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Title')),
                ('file', models.FileField(upload_to='documents')),
                ('url', models.URLField(blank=True, max_length=300, null=True, verbose_name='URL of file')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='company.documentcategory')),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'ordering': ['-id'],
            },
        ),
    ]
