# Generated by Django 3.1.6 on 2021-08-28 08:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Introduction'),
        ),
    ]
