# Generated by Django 3.1.6 on 2021-08-28 15:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210828_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='content_upload',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
