# Generated by Django 3.1.6 on 2021-08-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_introduction_content_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='image',
        ),
    ]
