# Generated by Django 3.1.6 on 2021-08-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_introduction_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introduction',
            name='content',
        ),
        migrations.AddField(
            model_name='introduction',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
