# Generated by Django 3.1.6 on 2021-09-06 09:04

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20210902_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='link',
            field=embed_video.fields.EmbedVideoField(max_length=500, null=True, verbose_name='Videos Url'),
        ),
    ]
