# Generated by Django 3.1.6 on 2021-09-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20210926_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chalani',
            name='image',
        ),
        migrations.RemoveField(
            model_name='darta',
            name='image',
        ),
        migrations.CreateModel(
            name='DartaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='darta/file')),
                ('darta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.darta')),
            ],
            options={
                'verbose_name_plural': 'Darta File',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ChalaniFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='chalani/file')),
                ('chalani', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.chalani')),
            ],
            options={
                'verbose_name_plural': 'Chalani File',
                'ordering': ['-id'],
            },
        ),
    ]
