# Generated by Django 3.1.6 on 2021-09-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20210926_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dartafile',
            name='darta',
        ),
        migrations.AddField(
            model_name='chalani',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='chalani-images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='darta',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='darta-images', verbose_name='Image'),
        ),
        migrations.DeleteModel(
            name='ChalaniFile',
        ),
        migrations.DeleteModel(
            name='DartaFile',
        ),
    ]
