# Generated by Django 3.1.6 on 2021-09-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20210927_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalani',
            name='medium',
            field=models.CharField(choices=[('E', 'Email'), ('H', 'Hard Copy')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='darta',
            name='medium',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sending Medium'),
        ),
    ]
