# Generated by Django 3.1.6 on 2021-09-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_auto_20210927_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuploadfile',
            name='types',
            field=models.CharField(choices=[('Cu', 'Current Budget'), ('Ca', 'Capital Budget')], max_length=2, null=True, verbose_name='Type of Files'),
        ),
    ]
