# Generated by Django 3.1.6 on 2021-09-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_auto_20210927_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chalani',
            name='date',
            field=models.CharField(max_length=80, verbose_name='Chalani Date'),
        ),
    ]
