# Generated by Django 3.1.6 on 2021-09-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20210928_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='darta',
            name='eng_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
