# Generated by Django 3.1.6 on 2021-10-04 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_darta_eng_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=40, verbose_name='Email'),
        ),
    ]
