# Generated by Django 3.1.6 on 2021-11-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_auto_20211004_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='chalani',
            name='chalani_perform_date',
            field=models.CharField(max_length=80, null=True, verbose_name='Chalani Date'),
        ),
        migrations.AlterField(
            model_name='chalani',
            name='medium',
            field=models.CharField(blank=True, choices=[('E', 'Email'), ('H', 'Hard Copy')], max_length=20, null=True),
        ),
    ]
