# Generated by Django 3.1.6 on 2021-03-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrazingEquipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Specification')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Brazing Equipments',
            },
        ),
        migrations.CreateModel(
            name='Cement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Cement',
            },
        ),
        migrations.CreateModel(
            name='CompactionTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Compaction Tests',
            },
        ),
        migrations.CreateModel(
            name='ConcreteAggregate10mm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Concrete Aggregate(10mm)',
            },
        ),
        migrations.CreateModel(
            name='ConcreteAggregate20mm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Concrete Aggregate(20mm)',
            },
        ),
        migrations.CreateModel(
            name='ConcreteAggregate40mm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Concrete Aggregate(40mm)',
            },
        ),
        migrations.CreateModel(
            name='ConcreteTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Concrete Tests',
            },
        ),
        migrations.CreateModel(
            name='ConcretingEquipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Specification')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Concreting Equipments',
            },
        ),
        migrations.CreateModel(
            name='CopperWaterStopperTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Copper Water Stopper Tests',
            },
        ),
        migrations.CreateModel(
            name='CoreDrilltest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('drilling_depth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Drilling Depth(m)')),
                ('depth_slightly_weatherd_gneiss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Depth Slightly Weatherd Gneiss(m)')),
                ('coordinate', models.CharField(blank=True, max_length=200, null=True, verbose_name='Co-ordinate')),
            ],
            options={
                'verbose_name_plural': 'Core Drill test',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('no_of_revisions', models.IntegerField(verbose_name='Number of Revisions')),
                ('name_of_major_work', models.CharField(max_length=200, verbose_name='Name of Major Work')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Design/Drawings',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='EarthFillingMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Earth Filling Material',
            },
        ),
        migrations.CreateModel(
            name='EarthMovingCompaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Specification')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Earth Moving Compaction',
            },
        ),
        migrations.CreateModel(
            name='FaceSlabBeddingMaterial2A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Face Slab Bedding Material 2A',
            },
        ),
        migrations.CreateModel(
            name='FaceSlabBeddingMaterial2B',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Face Slab Bedding Material 2B',
            },
        ),
        migrations.CreateModel(
            name='FineAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'FineAggregate',
            },
        ),
        migrations.CreateModel(
            name='Geophysical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Geophysical Investigation',
            },
        ),
        migrations.CreateModel(
            name='GeophysicalInvestigationEquipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Specification')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Geophysical Investigation Equipments',
            },
        ),
        migrations.CreateModel(
            name='GranularSubBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Granular Sub Base',
            },
        ),
        migrations.CreateModel(
            name='GroutingEquipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Specification')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Grouting Equipments',
            },
        ),
        migrations.CreateModel(
            name='GroutingTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Grouting Tests',
            },
        ),
        migrations.CreateModel(
            name='LabEquipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Specification')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Lab Equipments',
            },
        ),
        migrations.CreateModel(
            name='MethodOfStatements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description of Method of Statement')),
                ('no_of_revisions', models.IntegerField(verbose_name='Number of Revisions')),
                ('name_of_major_work', models.CharField(max_length=200, verbose_name='Name of Major Work')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Methods of Statements',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PermeabilityTests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Permeability Tests',
            },
        ),
        migrations.CreateModel(
            name='QADocumentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=600, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=600, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'QA/AC Documentation',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_report', models.CharField(max_length=200, verbose_name='Name of Report')),
                ('no_of_reports', models.IntegerField(verbose_name='Number of Reports')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Name of Report',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='RockFill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Rock Fill',
            },
        ),
        migrations.CreateModel(
            name='SecondClassRock1000MM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Second Class Rock 1000MM',
            },
        ),
        migrations.CreateModel(
            name='SmallSizeRock300MM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Small Size Rock Fill 300MM',
            },
        ),
        migrations.CreateModel(
            name='SmallSizeRock600MM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_test', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of Test')),
                ('no_of_test', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Number of Test')),
                ('test_standard', models.CharField(blank=True, max_length=100, null=True, verbose_name='Test Standard')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Small Size Rock Fill 600MM',
            },
        ),
        migrations.CreateModel(
            name='SurveyEquipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('specification', models.TextField(blank=True, null=True, verbose_name='Specification')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Survey Equipments',
            },
        ),
        migrations.CreateModel(
            name='TestFootages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_work', models.CharField(max_length=100, verbose_name='Name of Work')),
                ('clip', models.FileField(blank=True, null=True, upload_to='footages', verbose_name='Clip')),
                ('duration_of_clip', models.CharField(max_length=100, verbose_name='Duration of Clip')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Test Footages',
            },
        ),
        migrations.CreateModel(
            name='WorkFootages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_work', models.CharField(max_length=100, verbose_name='Name of Work')),
                ('clip', models.FileField(blank=True, null=True, upload_to='footages', verbose_name='Clip')),
                ('duration_of_clip', models.CharField(max_length=100, verbose_name='Duration of Clip')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks')),
            ],
            options={
                'verbose_name_plural': 'Work Footages',
            },
        ),
    ]
