# Generated by Django 3.0.3 on 2021-05-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testfootages',
            name='clip',
        ),
        migrations.RemoveField(
            model_name='workfootages',
            name='clip',
        ),
        migrations.AddField(
            model_name='testfootages',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL of file'),
        ),
        migrations.AddField(
            model_name='workfootages',
            name='url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='URL of file'),
        ),
    ]
